[webserver]
port = ":9090"              # port to bind the web server to. defaults ":8080"

	[webserver.headers]
	Access-Control-Allow-Origin = "*"
	Cache-Control = "no-cache, no-store, must-revalidate"

[cache]                     # configure a tile cache
type = "file"               # a file cache will cache to the local file system
basepath = "/tmp/tegola"    # where to write the file cache

# register data providers
[[providers]]
name = "transit"       # provider name is referenced from map layers (required)
type = "postgis"            # the type of data provider. currently only supports postgis (required)
host = "localhost"          # postgis database host (required)
port = 5432                 # postgis database port (required)
database = "transit_israel"         # postgis database name (required)
user = "irees"             # postgis database user (required)
password = ""               # postgis database password (required)
srid = 4326                 # The default srid for this provider. Defaults to WebMercator (3857) (optional)
max_connections = 50        # The max connections to maintain in the connection pool. Default is 100. (optional)
# ssl_mode = "prefer"        # PostgreSQL SSL mode*. Default is "disable". (optional)

	[[providers.layers]]
	name = "stops"           
	tablename = "gtfs_stops" 
	geometry_fieldname = "geometry"   
    geometry_type = "point"
	id_fieldname = "id"               
	srid = 4326                       

    [[providers.layers]]
    name = "shapes"
	geometry_fieldname = "geometry"  
    geometry_type = "linestring"
	id_fieldname = "id"              
	sql = "SELECT id, ST_AsBinary(ST_Force2D(geometry::geometry)) AS geometry FROM gtfs_shapes WHERE generated = 'f' AND geometry && !BBOX!"

# maps are made up of layers
[[maps]]
name = "transit"                           
	[[maps.layers]]
	name = "stops"                         
	provider_layer = "transit.stops"  
	min_zoom = 0                           
	max_zoom = 30                          
	[[maps.layers]]
	name = "shapes"                              
	provider_layer = "transit.shapes"  
	min_zoom = 0                       
	max_zoom = 30                      

