# Documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- main: ./cmd/gotransit/main.go
  env:
  - CGO_ENABLED=0
  - LDFLAGS="-L/usr/local/opt/sqlite/lib"
  - CPPFLAGS="-I/usr/local/opt/sqlite/include"
  flags:
    - -tags=sqlite
  goos:
  - darwin
  goarch:
  - amd64
# dockers:
#   - image_templates:
#     - interline-io/gotransit
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
