version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: snap install --classic goreleaser
      - run: goreleaser

workflows:
  version: 2
  untagged-test:
    jobs:
      - test
  tagged-build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
