name: Build releases
on: 
  push:
    tags:
      - '*'
jobs:
  goreleaser-ubuntu:
    # TODO: figure out how to have this depend on tests passing
    runs-on: [ubuntu-18.04]
    steps:
      - name: Install Ubuntu dependencies
        run: sudo apt-get install sqlite3 libsqlite3-dev libspatialite-dev
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOS: linux
          GOARCH: amd64
  goreleaser-macos:
    runs-on: [macOS-latest]
    steps:
      - name: Install macOS dependencies
        run: brew install sqlite libspatialite
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOS: darwin
          GOARCH: amd64
