name: Go
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Run tests
      run: go test -coverprofile c.out
    - name: Produce coverage report
      run: go tool cover -html=c.out -o coverage.html
    # TODO: add profiling
